version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: cargo
    container_name: cargo
    volumes:
      - ..:/app
    command: "sleep infinity"
    environment:
      NEO4J_BOLT_URL: "bolt://neo4j:cargo@neo4j:7687"
    networks:
      - dev
    depends_on:
      - neo4j

  # Neo4J UI URL: http://localhost:7474/browser/
  neo4j:
    image: neo4j
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: tackle
      NEO4J_AUTH: neo4j/cargo
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_security_procedures_whitelist: gds.*, apoc.*
      NEO4J_dbms_security_procedures_unrestricted: gds.*, apoc.*
    volumes:
      - neo4j:/data
    networks:
      - dev

volumes:
  neo4j:
    
networks:
  dev: null
